ideologies = [
//Centrist
    	{
        "name": "Centrism",
	    	"link": "https://en.wikipedia.org/wiki/Centrism",
		"desc": "Centrism is a political position that supports a balance between left-leaning and right-leaning policies. It opposes a significant shift in society.",
		"next": "Radical Centrism, Apoliticism, Neoliberalism, Center-Left Politics, Center-Right Politics",
        "stats": {
	  "econ": 0,
	  "govt": 0,
	  "econsys": 0,
	  "econreg": 0,
          "govtsize": 0,
          "govttype": 0,
          "diplapp": 0,
          "diplrel": 0,
          "sctychg": 0,
          "sctytrad": 0,
          "techacc": 0,
          "techbio": 0,
          "lawtype": 0,
          "lawrehab": 0,
          "cltrhrchy": 0,
          "cltrassi": 0,
          "proccomp": 0,
          "proctrans": 0,
          "polapol": -5,
          "polext": -5
        }
    },
	{
        "name": "Radical Centrism",
	    	"link": "https://en.wikipedia.org/wiki/Radical_centrism",
		"desc": "Radical Centrism is a political ideology that aims to borrow ideas from different sides, often merging them toghether to create an independent worldview.",
		"next": "Centrism, Apoliticism, Neoliberalism, Center-Left Politics, Center-Right Politics",
        "stats": {
	  "econ": 0,
	  "govt": 2,
	  "econsys": 0,
	  "econreg": 0,
          "govtsize": 2,
          "govttype": 0,
          "diplapp": 0,
          "diplrel": 0,
          "sctychg": 0,
          "sctytrad": 0,
          "techacc": 0,
          "techbio": 0,
          "lawtype": 0,
          "lawrehab": 0,
          "cltrhrchy": 0,
          "cltrassi": 0,
          "proccomp": 0,
          "proctrans": 0,
          "polapol": 0,
          "polext": 8
        }
    },
	{
        "name": "Apoliticism",
	    	"link": "https://en.wikipedia.org/wiki/Apoliticism",
		"desc": "Apoliticism is a apathy/antipathy towards most political views. Apoliticals are often neutral in most political views.",
		"next": "Centrism, Radical Centrism, Neoliberalism, Center-Left Politics, Center-Right Politics",
        "stats": {
	  "econ": 0,
	  "govt": 2,
	  "econsys": 0,
	  "econreg": 0,
          "govtsize": 2,
          "govttype": 0,
          "diplapp": 0,
          "diplrel": 0,
          "sctychg": 0,
          "sctytrad": 0,
          "techacc": 0,
          "techbio": 0,
          "lawtype": 0,
          "lawrehab": 0,
          "cltrhrchy": 0,
          "cltrassi": 0,
          "proccomp": 0,
          "proctrans": 0,
          "polapol": -10,
          "polext": -10
        }
    },
//LibLeft
	{
        "name": "Anarcho-Communism",
	    	"link": "https://en.wikipedia.org/wiki/Anarcho-communism",
		"desc": "Anarcho-Communism advocates the abolition of the state, capitalism, wage labour and private property, in favor of common ownership of the means of production and direct democracy.",
		"next": "Anarcho-Syndicalism, Anarcho-Collectivism, Anarchism, Libertarian Socialism",
        "stats": {
	  "econ": -9,
	  "govt": -9,
	  "econsys": -9,
	  "econreg": -9,
          "govtsize": -9,
          "govttype": 8,
          "diplapp": 0,
          "diplrel": 0,
          "sctychg": -7,
          "sctytrad": 0,
          "techacc": 0,
          "techbio": 0,
          "lawtype": 0,
          "lawrehab": 0,
          "cltrhrchy": -7,
          "cltrassi": 0,
          "proccomp": 0,
          "proctrans": -8,
          "polapol": 0,
          "polext": 7
        }
    },
	{
        "name": "Anarcho-Syndicalism",
	    	"link": "https://en.wikipedia.org/wiki/Anarcho-syndicalism",
		"desc": "Anarcho-Syndicalism views revolutionary industrial unionism as a method for workers in capitalist society to gain control of an economy and thus control influence in broader society, in order to asbolish the wage system.",
		"next": "Anarcho-Communism, Anarcho-Collectivism, Anarchism, Libertarian Socialism",
        "stats": {
	  "econ": -8,
	  "govt": -9,
	  "econsys": -8,
	  "econreg": -8,
          "govtsize": -8,
          "govttype": 8,
          "diplapp": 0,
          "diplrel": 0,
          "sctychg": -7,
          "sctytrad": 0,
          "techacc": 0,
          "techbio": 0,
          "lawtype": 0,
          "lawrehab": 0,
          "cltrhrchy": -3,
          "cltrassi": 0,
          "proccomp": 0,
          "proctrans": 2,
          "polapol": 0,
          "polext": 6
        }
    },
	{
        "name": "Anarcho-Collectivism",
	    	"link": "https://en.wikipedia.org/wiki/Collectivist_anarchism
		"desc": "Anarcho-Collectivism advocates the abolition of both the state and private ownership of the means of production as it envisions in its place the means of production being owned collectively whilst controlled and self-managed by the producers and workers themselves.",
		"next": "Anarcho-Communism, Anarcho-Syndicalism, Anarchism, Libertarian Socialism",
        "stats": {
	  "econ": -7,
	  "govt": -9,
	  "econsys": -7,
	  "econreg": -5,
          "govtsize": -9,
          "govttype": -2,
          "diplapp": 0,
          "diplrel": 0,
          "sctychg": -8,
          "sctytrad": 0,
          "techacc": 0,
          "techbio": 0,
          "lawtype": 0,
          "lawrehab": 0,
          "cltrhrchy": -3,
          "cltrassi": 0,
          "proccomp": 0,
          "proctrans": 2,
          "polapol": 0,
          "polext": 5
        }
    },
	{
        "name": "Anarcho-Primitivism",
	    	"link": "https://en.wikipedia.org/wiki/anarcho-primitivism
		"desc": "Anarcho-Primitivism is an anarchist critique of the origins and progress of civilization, and advocates for the de-industrialization of society, and the abolition of modern technology.",
		"next": "Anarcho-Communism, Anarchism, Anarcho-Mutualism",
        "stats": {
	  "econ": -3,
	  "govt": -9,
	  "econsys": -3,
	  "econreg": -5,
          "govtsize": -9,
          "govttype": -2,
          "diplapp": 0,
          "diplrel": 0,
          "sctychg": -8,
          "sctytrad": 0,
          "techacc": 9,
          "techbio": -9,
          "lawtype": 0,
          "lawrehab": 0,
          "cltrhrchy": -3,
          "cltrassi": 0,
          "proccomp": 0,
          "proctrans": 2,
          "polapol": 0,
          "polext": 5
        }
    },
	{
        "name": "Minarcho-Socialism",
	    	"link": "https://10groups.github.io/none.html",
		"desc": "Minarcho-Socialism advocates a state that is limited and minimal, but also based on socialist principles. Rather than providing law enforcement, a Minarcho-Socialist state would provide welfare and offer protection for workers.",
		"next": "Paleolibertarianism, Green Libertarianism, Minarchism, Classical Liberalism",
        "stats": {
	  "econ": -8,
	  "govt": -7,
	  "econsys": -8,
	  "econreg": -8,
          "govtsize": -7,
          "govttype": 5,
          "diplapp": 0,
          "diplrel": 0,
          "sctychg": -5,
          "sctytrad": -5,
          "techacc": 0,
          "techbio": 0,
          "lawtype": 0,
          "lawrehab": 0,
          "cltrhrchy": 7,
          "cltrassi": 0,
          "proccomp": 0,
          "proctrans": 0,
          "polapol": 0,
          "polext": 2
        }
    },
	{
        "name": "Libertarian Socialism",
	    	"link": "https://en.wikipedia.org/wiki/Anarcho-communism",
		"desc": "Libertarian Socialism is an anti-authoritarian, anti-statist and libertarian political philosophy within the socialist movement which rejects the state socialist conception of socialism as a statist form where the state retains centralized control of the economy.",
		"next": "Minarcho-Socialism, Anarcho-Collectivism, Anarchism, Anarcho-Communism",
        "stats": {
	  "econ": -5,
	  "govt": -5,
	  "econsys": -5,
	  "econreg": -5,
          "govtsize": -5,
          "govttype": 0,
          "diplapp": 0,
          "diplrel": 0,
          "sctychg": -5,
          "sctytrad": 0,
          "techacc": 0,
          "techbio": 0,
          "lawtype": 0,
          "lawrehab": 0,
          "cltrhrchy": -7,
          "cltrassi": 0,
          "proccomp": 0,
          "proctrans": 0,
          "polapol": 0,
          "polext": 2
        }
    },
	{
        "name": "Democratic Socialism",
	    	"link": "https://en.wikipedia.org/wiki/Democratic_socialism",
		"desc": "Democratic socialism is defined as having a socialist economy in which the means of production are mostly socially and collectively owned or controlled, alongside a democratic political system of government.",
		"next": "Libertarian Socialism, Social Democracy",
        "stats": {
	  "econ": -3,
	  "govt": -1,
	  "econsys": -3,
	  "econreg": -3,
          "govtsize": -1,
          "govttype": 0,
          "diplapp": 0,
          "diplrel": 0,
          "sctychg": -5,
          "sctytrad": 0,
          "techacc": 0,
          "techbio": 0,
          "lawtype": 0,
          "lawrehab": 0,
          "cltrhrchy": -1,
          "cltrassi": 0,
          "proccomp": 0,
          "proctrans": 0,
          "polapol": 0,
          "polext": -2
        }
    },
	{
        "name": "Social Democracy",
	    	"link": "https://en.wikipedia.org/wiki/Social_democracy",
		"desc": "Social Democracy supports political and economic democracy, and advocates strong welfare and higher taxation, especially for the wealthy.",
		"next": "Libertarian Socialism, Social Democracy",
        "stats": {
	  "econ": -2,
	  "govt": -1,
	  "econsys": -2,
	  "econreg": -2,
          "govtsize": -1,
          "govttype": 0,
          "diplapp": 0,
          "diplrel": 0,
          "sctychg": -5,
          "sctytrad": 0,
          "techacc": 0,
          "techbio": 0,
          "lawtype": 0,
          "lawrehab": 0,
          "cltrhrchy": -1,
          "cltrassi": 0,
          "proccomp": 0,
          "proctrans": 0,
          "polapol": 0,
          "polext": -2
        }
    },
	{
        "name": "Progressivism",
	    	"link": "https://en.wikipedia.org/wiki/Progressivism",
		"desc": "Progressivism is a political philosophy in support of social reform, and is based on the idea of progress and modernity.",
		"next": "Libertarian Socialism, Social Democracy",
        "stats": {
	  "econ": -1,
	  "govt": -1,
	  "econsys": -1,
	  "econreg": -1,
          "govtsize": -1,
          "govttype": 0,
          "diplapp": 0,
          "diplrel": 0,
          "sctychg": -7,
          "sctytrad": -7,
          "techacc": -5,
          "techbio": 0,
          "lawtype": 0,
          "lawrehab": 0,
          "cltrhrchy": -1,
          "cltrassi": 0,
          "proccomp": 0,
          "proctrans": 0,
          "polapol": 0,
          "polext": -2
        }
    },
	{
        "name": "Syndicalism",
	    	"link": "https://en.wikipedia.org/wiki/Anarcho-communism",
		"desc": "Syndicalism advocates the establishment of local worker-based organizations and the advancement of the demands and rights of workers through strikes.",
		"next": "Libertarian Socialism, Anarcho-Syndicalism, Minarcho-Socialism",
        "stats": {
	  "econ": -7,
	  "govt": -3,
	  "econsys": -7,
	  "econreg": -5,
          "govtsize": -3,
          "govttype": 0,
          "diplapp": 0,
          "diplrel": 0,
          "sctychg": -5,
          "sctytrad": 0,
          "techacc": 0,
          "techbio": 0,
          "lawtype": 0,
          "lawrehab": 0,
          "cltrhrchy": -7,
          "cltrassi": 0,
          "proccomp": 0,
          "proctrans": 0,
          "polapol": 0,
          "polext": 2
        }
    },
//LibCenter
	{
        "name": "Anarchism (Without Adjectives)",
	    	"link": "https://en.wikipedia.org/wiki/Anarchism",
		"desc": "Anarchism is a political philosophy and movement that rejects all involuntary, coercive forms of hierarchy. It calls for the 'abolition of unjust hierarchies', which can be interpreted differently based on one's economic beliefs.",
		"next": "Anarcho-Mutualism, Anarcho-Individualism",
        "stats": {
	  "econ": -2,
	  "govt": -9,
	  "econsys": -2,
	  "econreg": 0,
          "govtsize": 0,
          "govttype": 0,
          "diplapp": 0,
          "diplrel": 0,
          "sctychg": 0,
          "sctytrad": 0,
          "techacc": 0,
          "techbio": 0,
          "lawtype": 0,
          "lawrehab": 0,
          "cltrhrchy": 0,
          "cltrassi": 0,
          "proccomp": 0,
          "proctrans": 0,
          "polapol": 0,
          "polext": 5
        }
    },
	{
        "name": "Georgism",
	    	"link": "https://en.wikipedia.org/wiki/Georgism",
		"desc": "Georgism is an ideology that believes all land should belong equally to all members of society via a land tax.",
		"next": "Geolibertarianism, Mutualism, Social Democracy",
        "stats": {
	  "econ": 0,
	  "govt": -1,
	  "econsys": 0,
	  "econreg": 5,
          "govtsize": -1,
          "govttype": 0,
          "diplapp": 0,
          "diplrel": 0,
          "sctychg": -7,
          "sctytrad": 0,
          "techacc": 0,
          "techbio": 0,
          "lawtype": 0,
          "lawrehab": 0,
          "cltrhrchy": 0,
          "cltrassi": 0,
          "proccomp": 0,
          "proctrans": 0,
          "polapol": 0,
          "polext": -2
        }
    },
	{
        "name": "Geolibertarianism",
	    	"link": "https://en.wikipedia.org/wiki/Geolibertarianism",
		"desc": "Geolibertarianism is an ideology that integrates libertarianism with Georgism. They believe that a land tax should be the only tax.",
		"next": "Georgism, Mutualism, Libertarianism",
        "stats": {
	  "econ": 0,
	  "govt": -5,
	  "econsys": 0,
	  "econreg": 5,
          "govtsize": -5,
          "govttype": 0,
          "diplapp": 0,
          "diplrel": 0,
          "sctychg": -7,
          "sctytrad": 0,
          "techacc": 0,
          "techbio": 0,
          "lawtype": 0,
          "lawrehab": 0,
          "cltrhrchy": 0,
          "cltrassi": 0,
          "proccomp": 0,
          "proctrans": 0,
          "polapol": 0,
          "polext": -2
        }
    },
{
        "name": "Mutualism",
	    	"link": "https://en.wikipedia.org/wiki/Mutualism_(economic_theory)",
		"desc": "Mutualism is an anarchist school of thought and economic theory that advocates a socialist society based on free markets and usufructs, i.e. occupation and use property norms.",
		"next": "Georgism, Anarcho-Mutualism, Geolibertarianism",
        "stats": {
	  "econ": -2,
	  "govt": -5,
	  "econsys": -5,
	  "econreg": -8,
          "govtsize": -1,
          "govttype": 0,
          "diplapp": 0,
          "diplrel": 0,
          "sctychg": -8,
          "sctytrad": 0,
          "techacc": 0,
          "techbio": 0,
          "lawtype": 0,
          "lawrehab": 0,
          "cltrhrchy": 0,
          "cltrassi": 0,
          "proccomp": 0,
          "proctrans": 0,
          "polapol": 0,
          "polext": 2
        }
    },
	{
        "name": "Anarcho-Mutualism",
	    	"link": "https://10groups.github.io/none.html",
		"desc": "Mutualism is an anarchist school of thought and economic theory that advocates a socialist society based on free markets and usufructs, i.e. occupation and use property norms.",
		"next": "Geolibertarianism, Mutualism, Individualist Anarchism",
        "stats": {
	  "econ": -2,
	  "govt": -9,
	  "econsys": -5,
	  "econreg": -8,
          "govtsize": -9,
          "govttype": 0,
          "diplapp": 0,
          "diplrel": 0,
          "sctychg": -8,
          "sctytrad": 0,
          "techacc": 0,
          "techbio": 0,
          "lawtype": 0,
          "lawrehab": 0,
          "cltrhrchy": 0,
          "cltrassi": 0,
          "proccomp": 0,
          "proctrans": 0,
          "polapol": 0,
          "polext": 2
        }
    },
//LibRight
	{
        "name": "Technoliberalism",
	    	"link": "https://en.wikipedia.org/wiki/Technoliberalism",
		"desc": "Technoliberalism is a political philosophy that beleives that technology should be available to everyone without controls. It is also founded on core liberal beliefs like liberty, individualism, and economic freedom.",
		"next": "Liberalism, Classical Liberalism, Libertarianism",
        "stats": {
	  "econ": 7,
	  "govt": -3,
	  "econsys": 7,
	  "econreg": -7,
          "govtsize": -3,
          "govttype": 5,
          "diplapp": 0,
          "diplrel": 0,
          "sctychg": -5,
          "sctytrad": 0,
          "techacc": -8,
          "techbio": 0,
          "lawtype": 0,
          "lawrehab": 0,
          "cltrhrchy": 5,
          "cltrassi": 0,
          "proccomp": 0,
          "proctrans": 0,
          "polapol": 0,
          "polext": -5
        }
    },
    	{
        "name": "Classical Liberalism",
	    	"link": "https://en.wikipedia.org/wiki/Classical_liberalism",
		"desc": "Classical liberalism is a political ideology and a branch of liberalism which advocates civil liberties under the rule of law with an emphasis on economic freedom.",
		"next": "Liberalism, Neoliberalism, Libertarianism",
        "stats": {
	  "econ": 5,
	  "govt": -3,
	  "econsys": 5,
	  "econreg": -5,
          "govtsize": -3,
          "govttype": 7,
          "diplapp": 0,
          "diplrel": 0,
          "sctychg": 0,
          "sctytrad": 5,
          "techacc": 0,
          "techbio": 0,
          "lawtype": 0,
          "lawrehab": 0,
          "cltrhrchy": 5,
          "cltrassi": 0,
          "proccomp": 0,
          "proctrans": 0,
          "polapol": 0,
          "polext": -2
        }
    },
	{
        "name": "Liberalism",
	    	"link": "https://en.wikipedia.org/wiki/Liberalism",
		"desc": "Liberalism is a political and moral philosophy based on liberty, consent of the governed and equality before the law, and often supports generally support free markets, free trade, limited government, and Captalism. This is not to be confused with progressivism.",
		"next": "Classical Liberalism, Neoliberalism, Fiscal Conservatism",
        "stats": {
	  "econ": 7,
	  "govt": -1,
	  "econsys": 7,
	  "econreg": -7,
          "govtsize": -1,
          "govttype": 5,
          "diplapp": 0,
          "diplrel": 0,
          "sctychg": -5,
          "sctytrad": 0,
          "techacc": 0,
          "techbio": 0,
          "lawtype": 0,
          "lawrehab": 0,
          "cltrhrchy": 5,
          "cltrassi": 0,
          "proccomp": 0,
          "proctrans": 0,
          "polapol": 0,
          "polext": -5
        }
    },
	{
        "name": "Neoliberalism",
	    	"link": "https://en.wikipedia.org/wiki/Neoliberalism",
		"desc": "Neoliberalism advocates economic reform and free market capitalism, supporting policies like privatization, deregulation, and generally, though not always, support globalism and progressivism.",
		"next": "Liberalism, Classical Liberalism, Fiscal Conservatism, Centrism",
        "stats": {
	  "econ": 5,
	  "govt": 0,
	  "econsys": 5,
	  "econreg": -1,
          "govtsize": 0,
          "govttype": 3,
          "diplapp": 0,
          "diplrel": -5,
          "sctychg": -7,
          "sctytrad": -5,
          "techacc": 0,
          "techbio": 0,
          "lawtype": 0,
          "lawrehab": 0,
          "cltrhrchy": 5,
          "cltrassi": 0,
          "proccomp": 0,
          "proctrans": 0,
          "polapol": 0,
          "polext": -7
        }
    },
	{
        "name": "Libertarianism",
	    	"link": "https://en.wikipedia.org/wiki/Libertarianism",
		"desc": "Libertarianism is an ideology that seeks to maximize political freedom and autonomy, emphasizing individualism, freedom of choice and voluntary association.",
		"next": "Paleolibertarianism, Green Libertarianism, Minarchism, Classical Liberalism",
        "stats": {
	  "econ": 8,
	  "govt": -5,
	  "econsys": 8,
	  "econreg": -8,
          "govtsize": -5,
          "govttype": 5,
          "diplapp": 0,
          "diplrel": 0,
          "sctychg": -5,
          "sctytrad": -5,
          "techacc": 0,
          "techbio": 0,
          "lawtype": 0,
          "lawrehab": 0,
          "cltrhrchy": 7,
          "cltrassi": 0,
          "proccomp": 0,
          "proctrans": 0,
          "polapol": 0,
          "polext": 2
        }
    },
	{
        "name": "Paleolibertarianism",
	    	"link": "https://en.wikipedia.org/wiki/Paleolibertarianism",
		"desc": "Paleolibertarianism is a political philosophy and variety of right-libertarianism that combines traditional conservative cultural values and social philosophy with a libertarian opposition to government intervention.",
		"next": "Libertarianism, Green Libertarianism, Minarchism, Classical Liberalism",
        "stats": {
	  "econ": 8,
	  "govt": -5,
	  "econsys": 8,
	  "econreg": -8,
          "govtsize": -5,
          "govttype": 5,
          "diplapp": 0,
          "diplrel": 0,
          "sctychg": -5,
          "sctytrad": 5,
          "techacc": 0,
          "techbio": 0,
          "lawtype": 0,
          "lawrehab": 0,
          "cltrhrchy": 7,
          "cltrassi": 0,
          "proccomp": 0,
          "proctrans": 0,
          "polapol": 0,
          "polext": 2
        }
    },
	{
        "name": "Anarcho-Individualism",
	    	"link": "https://en.wikipedia.org/wiki/Anarcho-capitalism",
		"desc": "Anarcho-capitalism is a political ideology that advocates the elimination of the states in favor of private property and free markets. They believe any action should be legal as long as no individual is a victim of agression.",
		"next": "Hoppeanism, Pink Capitalism, Minarchism, Anarcho-Individualism",
        "stats": {
	  "econ": 5,
	  "govt": -10,
	  "econsys": 5,
	  "econreg": -9,
          "govtsize": -10,
          "govttype": 0,
          "diplapp": 0,
          "diplrel": 0,
          "sctychg": -8,
          "sctytrad": 0,
          "techacc": 0,
          "techbio": 0,
          "lawtype": 0,
          "lawrehab": 0,
          "cltrhrchy": 6,
          "cltrassi": 0,
          "proccomp": 0,
          "proctrans": 0,
          "polapol": 0,
          "polext": 9
        }
    },
	{
        "name": "Minarchism",
	    	"link": "https://en.wikipedia.org/wiki/Libertarianism",
		"desc": "Minarchism advocates a state that is limited and minimal, whose only functions are to act as an enforcer of the non-aggression principle by providing its citizens with the military, the police and courts, thereby protecting them from aggression, theft, breach of contract, fraud and enforcing property laws.",
		"next": "Paleolibertarianism, Green Libertarianism, Minarchism, Classical Liberalism",
        "stats": {
	  "econ": 8,
	  "govt": -7,
	  "econsys": 8,
	  "econreg": -8,
          "govtsize": -7,
          "govttype": 5,
          "diplapp": 0,
          "diplrel": 0,
          "sctychg": -5,
          "sctytrad": -5,
          "techacc": 0,
          "techbio": 0,
          "lawtype": 0,
          "lawrehab": 0,
          "cltrhrchy": 7,
          "cltrassi": 0,
          "proccomp": 0,
          "proctrans": 0,
          "polapol": 0,
          "polext": 2
        }
    },
	{
        "name": "Anarcho-Capitalism",
	    	"link": "https://en.wikipedia.org/wiki/Anarcho-capitalism",
		"desc": "Anarcho-capitalism is a political ideology that advocates the elimination of the states in favor of private property and free markets. They believe any action should be legal as long as no individual is a victim of agression.",
		"next": "Hoppeanism, Pink Capitalism, Minarchism, Anarcho-Individualism",
        "stats": {
	  "econ": 9,
	  "govt": -9,
	  "econsys": 9,
	  "econreg": -9,
          "govtsize": -9,
          "govttype": 2,
          "diplapp": 0,
          "diplrel": 0,
          "sctychg": -5,
          "sctytrad": 0,
          "techacc": 0,
          "techbio": 0,
          "lawtype": 0,
          "lawrehab": 0,
          "cltrhrchy": 7,
          "cltrassi": 0,
          "proccomp": 0,
          "proctrans": 0,
          "polapol": 0,
          "polext": 7
        }
    }
];
