questions = [
	

	//Economic
	    {
	        "question": "Oppression by corporations is more of a concern than oppression by governments.",
	        "effect": {
	            "econ": -5,
	            "govt": 0,
	            "econsys": -5,
	            "econreg": 5,
                "govtsize": 0,
                "govttype": 0,
                "diplapp": 0,
                "diplrel": 0,
                "sctychg": 0,
                "sctytrad": 0,
                "techacc": 0,
                "techbio": 0,
                "lawtype": 0,
                "lawrehab": 0,
                "cltrhrchy": 0,
                "cltrassi": 0,
                "proccomp": 0,
                "proctrans": 0,
                "polapol": 0,
                "polext": 0               
	        }
	    },
	    {
	        "question": "It is necessary for the government to intervene in the economy to protect consumers.",
	        "effect": {
	            "econ": -5,
	            "govt": 0,
	            "econsys": 0,
	            "econreg": 5,
                "govtsize": 0,
                "govttype": 0,
                "diplapp": 0,
                "diplrel": 0,
                "sctychg": 0,
                "sctytrad": 0,
                "techacc": 0,
                "techbio": 0,
                "lawtype": 0,
                "lawrehab": 0,
                "cltrhrchy": 0,
                "cltrassi": 0,
                "proccomp": 0,
                "proctrans": 0,
                "polapol": 0,
                "polext": 0
	        }
	    },
	    {
	        "question": "The market regulates itself, since unjust monopolies are punished by bankrupcy.",
	        "effect": {
	            "econ": 5,
	            "govt": 0,
	            "econsys": 0,
	            "econreg": -5,
                "govtsize": 0,
                "govttype": 0,
                "diplapp": 0,
                "diplrel": 0,
                "sctychg": 0,
                "sctytrad": 0,
                "techacc": 0,
                "techbio": 0,
                "lawtype": 0,
                "lawrehab": 0,
                "cltrhrchy": 0,
                "cltrassi": 0,
                "proccomp": 0,
                "proctrans": 0,
                "polapol": 0,
                "polext": 0
	        }
	    },
	    {
	        "question": "Governmental social programs should be replaced with private charities and organizations.",
	        "effect": {
	            "econ": 5,
	            "govt": -5,
	            "econsys": 5,
	            "econreg": 0,
                "govtsize": 0,
                "govttype": 0,
                "diplapp": 0,
                "diplrel": 0,
                "sctychg": 0,
                "sctytrad": 0,
                "techacc": 0,
                "techbio": 0,
                "lawtype": 0,
                "lawrehab": 0,
                "cltrhrchy": 0,
                "cltrassi": 0,
                "proccomp": 0,
                "proctrans": 0,
                "polapol": 0,
                "polext": 0
	        }
	    },
	    {
	        "question": "From each according to his ability, to each according to his needs.",
	        "effect": {
	            "econ": -5,
	            "govt": 0,
	            "econsys": -5,
	            "econreg": 0,
                "govtsize": 0,
                "govttype": 0,
                "diplapp": 0,
                "diplrel": 0,
                "sctychg": 0,
                "sctytrad": 0,
                "techacc": 0,
                "techbio": 0,
                "lawtype": 0,
                "lawrehab": 0,
                "cltrhrchy": 0,
                "cltrassi": 0,
                "proccomp": 0,
                "proctrans": 0,
                "polapol": 0,
                "polext": 0
	        }
	    },
	    {
	        "question": "I support the abolition of a minimum wage.",
	        "effect": {
	            "econ": 5,
	            "govt": 0,
	            "econsys": 0,
	            "econreg": -10,
                "govtsize": 0,
                "govttype": 0,
                "diplapp": 0,
                "diplrel": 0,
                "sctychg": 0,
                "sctytrad": 0,
                "techacc": 0,
                "techbio": 0,
                "lawtype": 0,
                "lawrehab": 0,
                "cltrhrchy": 0,
                "cltrassi": 0,
                "proccomp": 0,
                "proctrans": 0,
                "polapol": 0,
                "polext": 0
	        }
	    },
	    {
	        "question": "The market should provide healthcare, instead of the government.",
	        "effect": {
	            "econ": 5,
	            "govt": 0,
	            "econsys": 5,
	            "econreg": -5,
                "govtsize": 0,
                "govttype": 0,
                "diplapp": 0,
                "diplrel": 0,
                "sctychg": 0,
                "sctytrad": 0,
                "techacc": 0,
                "techbio": 0,
                "lawtype": 0,
                "lawrehab": 0,
                "cltrhrchy": 0,
                "cltrassi": 0,
                "proccomp": 0,
                "proctrans": 0,
                "polapol": 0,
                "polext": 0
	        }
	    },
	    {
	        "question": "A government-controlled economy is generally better than that of an unregulated economy.",
	        "effect": {
	            "econ": -5,
	            "govt": 0,
	            "econsys": 0,
	            "econreg": 5,
                "govtsize": 0,
                "govttype": 0,
                "diplapp": 0,
                "diplrel": 0,
                "sctychg": 0,
                "sctytrad": 0,
                "techacc": 0,
                "techbio": 0,
                "lawtype": 0,
                "lawrehab": 0,
                "cltrhrchy": 0,
                "cltrassi": 0,
                "proccomp": 0,
                "proctrans": 0,
                "polapol": 0,
                "polext": 0
	        }
	    },
	    {
	        "question": "Taxing citizens using involuntary methods can be considered an act of Theft or Violence.",
	        "effect": {
	            "econ": 5,
	            "govt": 0,
	            "econsys": 5,
	            "econreg": -5,
                "govtsize": 0,
                "govttype": 0,
                "diplapp": 0,
                "diplrel": 0,
                "sctychg": 0,
                "sctytrad": 0,
                "techacc": 0,
                "techbio": 0,
                "lawtype": 0,
                "lawrehab": 0,
                "cltrhrchy": 0,
                "cltrassi": 0,
                "proccomp": 0,
                "proctrans": 0,
                "polapol": 0,
                "polext": 0
	        }
	    },
	    {
	        "question": "The means of production should belong to the workers.",
	        "effect": {
	            "econ": -5,
	            "govt": 0,
	            "econsys": -5,
	            "econreg": 0,
                "govtsize": 0,
                "govttype": 0,
                "diplapp": 0,
                "diplrel": 0,
                "sctychg": 0,
                "sctytrad": 0,
                "techacc": 0,
                "techbio": 0,
                "lawtype": 0,
                "lawrehab": 0,
                "cltrhrchy": 0,
                "cltrassi": 0,
                "proccomp": 0,
                "proctrans": 0,
                "polapol": 0,
                "polext": 0
	        }
	    },
	    {
	        "question": "Roads and Electricity should be publicly owned.",
	        "effect": {
	            "econ": -5,
	            "govt": 0,
	            "econsys": -5,
	            "econreg": 0,
                "govtsize": 0,
                "govttype": 0,
                "diplapp": 0,
                "diplrel": 0,
                "sctychg": 0,
                "sctytrad": 0,
                "techacc": 0,
                "techbio": 0,
                "lawtype": 0,
                "lawrehab": 0,
                "cltrhrchy": 0,
                "cltrassi": 0,
                "proccomp": 0,
                "proctrans": 0,
                "polapol": 0,
                "polext": 0
	        }
	    },
	    {
	        "question": "A regulated market is unfair for corporations, and ultimately, the people.",
	        "effect": {
	            "econ": 5,
	            "govt": 0,
	            "econsys": 0,
	            "econreg": -5,
                "govtsize": 0,
                "govttype": 0,
                "diplapp": 0,
                "diplrel": 0,
                "sctychg": 0,
                "sctytrad": 0,
                "techacc": 0,
                "techbio": 0,
                "lawtype": 0,
                "lawrehab": 0,
                "cltrhrchy": 0,
                "cltrassi": 0,
                "proccomp": 0,
                "proctrans": 0,
                "polapol": 0,
                "polext": 0
	        }
	    },
	    {
	        "question": "The Justice System should be partially privatized, or even fully privatized.",
	        "effect": {
	            "econ": 5,
	            "govt": 0,
	            "econsys": 10,
	            "econreg": 0,
                "govtsize": 0,
                "govttype": 0,
                "diplapp": 0,
                "diplrel": 0,
                "sctychg": 0,
                "sctytrad": 0,
                "techacc": 0,
                "techbio": 0,
                "lawtype": 0,
                "lawrehab": 0,
                "cltrhrchy": 0,
                "cltrassi": 0,
                "proccomp": 0,
                "proctrans": 0,
                "polapol": 0,
                "polext": 0
	        }
	    },
	    {
	        "question": "Inheritance is a legitimate form of wealth.",
	        "effect": {
	            "econ": 5,
	            "govt": 0,
	            "econsys": 10,
	            "econreg": 0,
                "govtsize": 0,
                "govttype": 0,
                "diplapp": 0,
                "diplrel": 0,
                "sctychg": 0,
                "sctytrad": 0,
                "techacc": 0,
                "techbio": 0,
                "lawtype": 0,
                "lawrehab": 0,
                "cltrhrchy": 0,
                "cltrassi": 0,
                "proccomp": 0,
                "proctrans": 0,
                "polapol": 0,
                "polext": 0
	        }
	    },
	    //Governmental
	    {
	        "question": "A strong and good leadership is more beneficial than a democratic system.",
	        "effect": {
	            "econ": 0,
	            "govt": 5,
	            "govttype": -5,
	            "govtsize": 0,
                "econsys": 0,
                "econreg": 0,
                "diplapp": 0,
                "diplrel": 0,
                "sctychg": 0,
                "sctytrad": 0,
                "techacc": 0,
                "techbio": 0,
                "lawtype": 0,
                "lawrehab": 0,
                "cltrhrchy": 0,
                "cltrassi": 0,
                "proccomp": 0,
                "proctrans": 0,
                "polapol": 0,
                "polext": 0
	        }
	    },
	    {
	        "question": "Democracy is the least worst system for leadership.",
	        "effect": {
	            "econ": 0,
	            "govt": 5,
	            "govttype": 5,
	            "govtsize": 0,
                "econsys": 0,
                "econreg": 0,
                "diplapp": 0,
                "diplrel": 0,
                "sctychg": 0,
                "sctytrad": 0,
                "techacc": 0,
                "techbio": 0,
                "lawtype": 0,
                "lawrehab": 0,
                "cltrhrchy": 0,
                "cltrassi": 0,
                "proccomp": 0,
                "proctrans": 0,
                "polapol": 0,
                "polext": 0
	        }
	    },
	    {
	        "question": "A beneficial democracy requires high levels of education.",
	        "effect": {
	            "econ": 0,
	            "govt": 5,
	            "govttype": -5,
	            "govtsize": 0,
                "econsys": 0,
                "econreg": 0,
                "diplapp": 0,
                "diplrel": 0,
                "sctychg": 0,
                "sctytrad": 0,
                "techacc": 0,
                "techbio": 0,
                "lawtype": 0,
                "lawrehab": 0,
                "cltrhrchy": 0,
                "cltrassi": 0,
                "proccomp": 0,
                "proctrans": 0,
                "polapol": 0,
                "polext": 0
	        }
	    },
	    {
	        "question": "The government is required for a well-functioning society to exist.",
	        "effect": {
	            "econ": 0,
	            "govt": 5,
	            "govttype": 0,
	            "govtsize": 5,
                "econsys": 0,
                "econreg": 0,
                "diplapp": 0,
                "diplrel": 0,
                "sctychg": 0,
                "sctytrad": 0,
                "techacc": 0,
                "techbio": 0,
                "lawtype": 0,
                "lawrehab": 0,
                "cltrhrchy": 0,
                "cltrassi": 0,
                "proccomp": 0,
                "proctrans": 0,
                "polapol": 0,
                "polext": 0
	        }
	    },
	    {
	        "question": "Violence is not acceptable when protesting a government.",
	        "effect": {
	            "econ": 0,
	            "govt": 5,
	            "govttype": 0,
	            "govtsize": 5,
                "econsys": 0,
                "econreg": 0,
                "diplapp": 0,
                "diplrel": 0,
                "sctychg": 0,
                "sctytrad": 0,
                "techacc": 0,
                "techbio": 0,
                "lawtype": 0,
                "lawrehab": 0,
                "cltrhrchy": 0,
                "cltrassi": 0,
                "proccomp": 0,
                "proctrans": 0,
                "polapol": 0,
                "polext": 0
	        }
	    },
	    {
	        "question": "The sacrifice of some civil liberties is necessary to protect us from acts of terrorism.",
	        "effect": {
	            "econ": 0,
	            "govt": 5,
	            "govttype": 0,
	            "govtsize": 5,
                "econsys": 0,
                "econreg": 0,
                "diplapp": 0,
                "diplrel": 0,
                "sctychg": 0,
                "sctytrad": 0,
                "techacc": 0,
                "techbio": 0,
                "lawtype": 0,
                "lawrehab": 0,
                "cltrhrchy": 0,
                "cltrassi": 0,
                "proccomp": 0,
                "proctrans": 0,
                "polapol": 0,
                "polext": 0
	        }
	    },
	    {
	        "question": "Any action that does not impose agression on any person should not be considered a criminal offence.",
	        "effect": {
	            "econ": 0,
	            "govt": -5,
	            "govttype": 0,
	            "govtsize": -5,
                "econsys": 0,
                "econreg": 0,
                "diplapp": 0,
                "diplrel": 0,
                "sctychg": 0,
                "sctytrad": 0,
                "techacc": 0,
                "techbio": 0,
                "lawtype": 0,
                "lawrehab": 0,
                "cltrhrchy": 0,
                "cltrassi": 0,
                "proccomp": 0,
                "proctrans": 0,
                "polapol": 0,
                "polext": 0
	        }
	    },
	    {
	        "question": "People should be willing to sacrifice their liberty for Security and Prosperity.",
	        "effect": {
	            "econ": 0,
	            "govt": 5,
	            "govttype": 0,
	            "govtsize": 5,
                "econsys": 0,
                "econreg": 0,
                "diplapp": 0,
                "diplrel": 0,
                "sctychg": 0,
                "sctytrad": 0,
                "techacc": 0,
                "techbio": 0,
                "lawtype": 0,
                "lawrehab": 0,
                "cltrhrchy": 0,
                "cltrassi": 0,
                "proccomp": 0,
                "proctrans": 0,
                "polapol": 0,
                "polext": 0
	        }
	    },
	    {
	        "question": "All authority should be questioned.",
	        "effect": {
	            "econ": 0,
	            "govt": -5,
	            "govttype": 0,
	            "govtsize": -5,
                "econsys": 0,
                "econreg": 0,
                "diplapp": 0,
                "diplrel": 0,
                "sctychg": 0,
                "sctytrad": 0,
                "techacc": 0,
                "techbio": 0,
                "lawtype": 0,
                "lawrehab": 0,
                "cltrhrchy": 0,
                "cltrassi": 0,
                "proccomp": 0,
                "proctrans": 0,
                "polapol": 0,
                "polext": 0
	        }
	    },
	    {
	        "question": "The existence of the state is a violation of our liberty and rights.",
	        "effect": {
	            "econ": 0,
	            "govt": -5,
	            "govttype": 0,
	            "govtsize": -5,
                "econsys": 0,
                "econreg": 0,
                "diplapp": 0,
                "diplrel": 0,
                "sctychg": 0,
                "sctytrad": 0,
                "techacc": 0,
                "techbio": 0,
                "lawtype": 0,
                "lawrehab": 0,
                "cltrhrchy": 0,
                "cltrassi": 0,
                "proccomp": 0,
                "proctrans": 0,
                "polapol": 0,
                "polext": 0
	        }
	    },
	    //Nationalism
		{
	        "question": "I support Regional Unions, like the European Union.",
	        "effect": {
	        "econ": 0,
	        "govt": 0,
	        "econsys": 0,
	        "econreg": 0,
                "govtsize": 0,
                "govttype": 0,
                "diplapp": 0,
                "diplrel": -5,
                "sctychg": 0,
                "sctytrad": 0,
                "techacc": 0,
                "techbio": 0,
                "lawtype": 0,
                "lawrehab": 0,
                "cltrhrchy": 0,
                "cltrassi": 0,
                "proccomp": 0,
                "proctrans": 0,
                "polapol": 0,
                "polext": 0
	        }
	    },
		{
	        "question": "My religious and political values should be spread as much as possible.",
	        "effect": {
	        "econ": 0,
	        "govt": 0,
	        "econsys": 0,
	        "econreg": 0,
                "govtsize": 0,
                "govttype": 0,
                "diplapp": -5,
                "diplrel": 0,
                "sctychg": 0,
                "sctytrad": 0,
                "techacc": 0,
                "techbio": 0,
                "lawtype": 0,
                "lawrehab": 0,
                "cltrhrchy": 0,
                "cltrassi": 0,
                "proccomp": 0,
                "proctrans": 0,
                "polapol": 0,
                "polext": 0
	        }
	    },
	{
	        "question": "Countries with authoritarian governments should be denounced and invaded.",
	        "effect": {
	        "econ": 0,
	        "govt": 0,
	        "econsys": 0,
	        "econreg": 0,
                "govtsize": 0,
                "govttype": 0,
                "diplapp": -5,
                "diplrel": 0,
                "sctychg": 0,
                "sctytrad": 0,
                "techacc": 0,
                "techbio": 0,
                "lawtype": 0,
                "lawrehab": 0,
                "cltrhrchy": 0,
                "cltrassi": 0,
                "proccomp": 0,
                "proctrans": 0,
                "polapol": 0,
                "polext": 0
	        }
	    },
	    {
	        "question": "Different countries and cultures have different preferences for the type of government.",
	        "effect": {
	        "econ": 0,
	        "govt": 0,
	        "econsys": 0,
	        "econreg": 0,
                "govtsize": 0,
                "govttype": 0,
                "diplapp": 5,
                "diplrel": 0,
                "sctychg": 0,
                "sctytrad": 0,
                "techacc": 0,
                "techbio": 0,
                "lawtype": 0,
                "lawrehab": 0,
                "cltrhrchy": 0,
                "cltrassi": 0,
                "proccomp": 0,
                "proctrans": 0,
                "polapol": 0,
                "polext": 0
	        }
	    },
		{
	        "question": "The United Nations needs more power.",
	        "effect": {
	        "econ": 0,
	        "govt": 0,
	        "econsys": 0,
	        "econreg": 0,
                "govtsize": 0,
                "govttype": -5,
                "diplapp": 0,
                "diplrel": 0,
                "sctychg": 0,
                "sctytrad": 0,
                "techacc": 0,
                "techbio": 0,
                "lawtype": 0,
                "lawrehab": 0,
                "cltrhrchy": 0,
                "cltrassi": 0,
                "proccomp": 0,
                "proctrans": 0,
                "polapol": 0,
                "polext": 0
	        }
	    },
	    {
	        "question": "A global nation where all countries are united will be beneficial to humanity.",
	        "effect": {
	        "econ": 0,
	        "govt": 0,
	        "econsys": 0,
	        "econreg": 0,
                "govtsize": 0,
                "govttype": -5,
                "diplapp": 0,
                "diplrel": 0,
                "sctychg": 0,
                "sctytrad": 0,
                "techacc": 0,
                "techbio": 0,
                "lawtype": 0,
                "lawrehab": 0,
                "cltrhrchy": 0,
                "cltrassi": 0,
                "proccomp": 0,
                "proctrans": 0,
                "polapol": 0,
                "polext": 0
	        }
	    },
		{
	        "question": "National sovereignty is very important.",
	        "effect": {
	        "econ": 0,
	        "govt": 0,
	        "econsys": 0,
	        "econreg": 0,
                "govtsize": 0,
                "govttype": 5,
                "diplapp": 0,
                "diplrel": 0,
                "sctychg": 0,
                "sctytrad": 0,
                "techacc": 0,
                "techbio": 0,
                "lawtype": 0,
                "lawrehab": 0,
                "cltrhrchy": 0,
                "cltrassi": 0,
                "proccomp": 0,
                "proctrans": 0,
                "polapol": 0,
                "polext": 0
	        }
	    },
	    //Ending
	    {
	        "question": "Marxism is too idealist, and is an ideology that would never work in practise.",
	        "effect": {
	        "econ": 5,
	        "govt": 0,
	        "econsys": 0,
	        "econreg": -5,
                "govtsize": 0,
                "govttype": 0,
                "diplapp": 0,
                "diplrel": 0,
                "sctychg": 0,
                "sctytrad": 0,
                "techacc": 0,
                "techbio": 0,
                "lawtype": 0,
                "lawrehab": 0,
                "cltrhrchy": 0,
                "cltrassi": 0,
                "proccomp": 0,
                "proctrans": 0,
                "polapol": 0,
                "polext": 0
	        }
	    }
	];

